#cloud-config

# TODO: pass arguments to server

users:
- name: ${service_name}
  uid: 2000

write_files:

# https://cloud.google.com/container-optimized-os/docs/how-to/firewall
- path: /etc/systemd/system/config-firewall.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=Configures the host firewall

    [Service]
    Type=oneshot
    RemainAfterExit=true
    ExecStart=/sbin/iptables -A INPUT -p tcp \
              %{~ for host_port, c in host_to_container_ports ~}
              --match multiport --dports ${host_port} \
              %{~ endfor ~}
              -j ACCEPT

- path: /etc/systemd/system/${service_name}.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=${service_name} service
    After=docker.service config-firewall.service
    Wants=docker.service config-firewall.service

    [Service]
    Restart=always
    Environment="HOME=/home/${service_name}"
    ExecStartPre=/usr/bin/docker-credential-gcr configure-docker
    ExecStart=/usr/bin/docker run --name=${service_name} \
                                  --log-opt tag=\"${container_image_name}#{{.Name}}\" \
                                  --rm \
                                  --user 2000 \
                                  %{~ for host_port, container_port in host_to_container_ports ~}
                                  --publish ${host_port}:${container_port} \
                                  %{~ endfor ~}
                                  %{~ for name, value in env ~}
                                  --env ${name}=${value} \
                                  %{~ endfor ~}
                                  ${container_image_name} ${ join(" ", args) }
    ExecStop=/usr/bin/docker stop ${service_name}
    ExecStopPost=/usr/bin/docker rm ${service_name}

runcmd:
- systemctl daemon-reload
- systemctl start ${service_name}.service

# Optional once-per-boot setup. For example: mounting a PD.
# bootcmd:
# - fsck.ext4 -tvy /dev/[DEVICE_ID]
# - mkdir -p /mnt/disks/[MNT_DIR]
# - mount -t ext4 -O ... /dev/[DEVICE_ID] /mnt/disks/[MNT_DIR]
